server:
  port: 8001

spring:
  application:
    name: im-study-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      initialization-fail-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HikariCP
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: root
  secretKey: rootroot
  bucketName: im-study

knife4j:
  enable: true
  openapi:
    title: im-study-auth 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.tiv.im.study.auth.controller